# Generated by Django 5.2 on 2025-04-18 02:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150)),
                ('accion', models.CharField(max_length=255)),
                ('modulo', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
